server:
  port: 80

spring:
  application:
    name: emall-facade
  redis:
    host: redis.middleware.emall.docker
    port: 6379
    password:
    database: 0
  zipkin:
    base-url: http://zipkin.middleware.emall.docker:9411
  sleuth:
    sampler:
      probability: 1.0

dubbo:
  application:
    name: emall-facade
  registry:
    address: zookeeper://zookeeper.middleware.emall.docker:2181
  consumer:
    check: false
    lazy: true
    timeout: 10000
    filter: tracing

jwt:
  authorizationType: Bearer
  secret: test
  ttl: 1440

management:
  endpoints:
    web:
      exposure:
        include: '*'
