spring:
  datasource:
    url: jdbc:mysql://10.10.24.122:3306/user_db?characterEncoding=utf-8&useSSL=false
    username: zuzhi_dev
    password: meZvE3KTGZiJYG
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
mybatis:
  type-aliases-package: org.emall.user.model
  mapper-locations: classpath:mapper/*.xml
dubbo:
  application:
    name: emall-user-provider
  registry:
    address: zookeeper://localhost:2181