/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('vue-amazing-ui')['Button']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputSearch: typeof import('vue-amazing-ui')['InputSearch']
    Search: typeof import('./src/components/Search.vue')['default']
    Space: typeof import('vue-amazing-ui')['Space']
    Tag: typeof import('vue-amazing-ui')['Tag']
  }
}
