server:
  port: 80
spring:
  redis:
    host: redis.middleware.emall.docker
    port: 6379
    password:
    database: 0
  application:
    name: emall-facade
dubbo:
  application:
    name: emall-facade
  registry:
    address: zookeeper://zookeeper.middleware.emall.docker:2181
  consumer:
    check: false
    lazy: true
    timeout: 1000000
jwt:
  authorizationType: Bearer
  secret: test
  ttl: 1440