spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  application:
    name: emall-facade
dubbo:
  application:
    name: emall-facade
  registry:
    address: zookeeper://localhost:2181
server:
  port: 80